version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_depot_app
          POSTGRES_PASSWORD: ""



    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Configure Bundler and install dependencies
          command: |
                gem update --system
                gem install bundler

      - run:
          name: Which bundler?
          command: bundle -v

      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment

      - run: mkdir test-reports
      # - run:
      #     name: Download Selenium
      #     command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      # - run:
      #     name: Start Selenium
      #     command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
      #     background: true
      -run:
        name: create database
        command: createdb rails_depot_app

      - run:
          name: run Migration
          command: rails db:migrate

      - run:
          name: run database
          command: rails db:seed

      - run:
          name: start rspec
          command: rspec

    pre-steps:
      - run:
          name: "Install git and SSH client"
          command: |
            apk add \
                --update \
                --no-progress \
                git \
                openssh-client
