version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Configure Bundler and install dependencies
          command: |
                gem update --system
                gem install bundler

      - run:
          name: Which bundler?
          command: bundle -v

      # - run:
      #     name: Bundle Install
      #     command: bundle check --path vendor/bundle || bundle install --deployment

    pre-steps:
      - run:
          name: "Install git and SSH client"
          command: |
            apk add \
                --update \
                --no-progress \
                git \
                openssh-client
