version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      # - run:
      #     name: Which bundler?
      #     command: bundle -v

      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment

    pre-steps:
      - run:
          name: "Install git and SSH client"
          command: |
            apk add \
                --update \
                --no-progress \
                git \
                openssh-client
