// Generated by CoffeeScript 1.12.7
(function() {
  var cart, notice;

  cart = document.getElementById("cart");

  cart.innerHTML = "<%= j render(@cart) %>";

  notice = document.getElementById("notice");

  if (notice) {
    notice.style.display = "none";
  }

}).call(this);
