// Generated by CoffeeScript 1.12.7
(function() {
  var cart;

  cart = document.getElementById("cart");

  console.log("BEFORE INNERHTML CALL");

  console.log(cart.innerHTML);

  cart.innerHTML = "<% if session[:hide_cart] %>" + "<%= j render_if @cart && @cart.line_items.any?, 'carts/cart_hidden' %>" + "<% else %>" + "<%= j render_if @cart && @cart.line_items.any?, @cart %>" + "<% end %>";

  console.log("AFTER INNERHTML CALL");

  console.log(cart.innerHTML);

}).call(this);
